### ISSUE TITLE
Using app with own files

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [MadsHolten/sparql-visualizer#10]
Hi Mads!

great app still!

I have some problems setting up the app via github

I prepared a GoodRelations example here: [link](https://github.com/w3c-lbd-cg/product/blob/develop/GRPropertyViz.json)

I created the ragithubuser link URI encoded:

https://madsholten.github.io/sparql-visualizer/?file=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c-lbd-cg%2Fproduct%2Fdevelop%2FGRPropertyViz.json

However it does not seem to work and jump to a default version. Any suggestions?

**Comment by mathib** [comment]
https://madsholten.github.io/sparql-visualizer/?file=https:%2F%2Fdl.dropbox.com%2Fs%2F9e8d1b194yzyqbg%2Fgeorg_ex.json works :)
You just forgot that the last line of the triples does not need a comma

**Comment by mathib** [comment]
@MadsHolten There is some problem when SPARQL keywords are not all in capital or not-in-capital. Georg used for example 'Select' instead of 'SELECT' or 'select', which causes the query to fail...

@GeorgFerdinandSchneider Try using CONSTRUCT queries to show the results in graph form :)

**Comment by GeorgFerdinandSchneider** [comment]
Yay I will be more careful with my JSON next time!

I still get the error with Matthias link above [GR Example](https://madsholten.github.io/sparql-visualizer/?file=https:%2F%2Fdl.dropbox.com%2Fs%2F9e8d1b194yzyqbg%2Fgeorg_ex.json) SyntaxError: Expected [1] QueryUnit or [29] UpdateUnit but "S" found. 

also there should be some Triples appearing from GR ontology

**Comment by mathib** [comment]
@GeorgFerdinandSchneider there seems to be some problem when you enter 'Select' instead of 'SELECT' or 'select'. The latter works!

**Comment by GeorgFerdinandSchneider** [comment]
Any hints I adapted from https://github.com/w3c-lbd-cg/product/blob/develop/vis-data.json

The current version is https://raw.githubusercontent.com/w3c-lbd-cg/product/develop/GRPropertyViz.json

It still seems to be not working!?

**Comment by mathib** [comment]
Again a comma too much :) No comma at the end of the last line of a bunch of strings (even if it's only one line). It helps if you use a code editor to spot those errors quickly!

https://madsholten.github.io/sparql-visualizer/?file=https:%2F%2Fdl.dropbox.com%2Fs%2Fvvn4izxvv3o105u%2FGRPropertyViz.json

**Comment by MadsHolten** [comment]
Good discussion you guys are having here. Regarding the Select problem, please submit an issue to [rdfstore](https://github.com/antoniogarrote/rdfstore-js) which is the library I use for queries. Unfortunately, it has not been updated since 2016, so probably it will not be solved. We really need a better alternative.

**Comment by mathib** [comment]
@MadsHolten This can also be solved by sanitizing the query in the app, before it is send to the rdfstore or Stardog db?

**Comment by GeorgFerdinandSchneider** [comment]
Dear all!

I think it fine to close this issue. The novel video and textual documentation provides the means to get the app running. Thanks for your pointers and comments!

closed()
