### ISSUE TITLE
Table column should have larger margins

### ISSUE THREAD

**Issue by mathib** [MadsHolten/sparql-visualizer#4]
![image](https://user-images.githubusercontent.com/22965460/35558778-2d76e9f2-05a9-11e8-8748-1a0f3dff8aa3.png)

**Comment by mathib** [comment]
Or a horizontal scrollbar

**Comment by mathib** [comment]
Yep, already posted it here: https://github.com/MadsHolten/sparql-visualizer/issues/5 

If you use global prefixes, make sure that users can change them and also make sure they don't collide with leftover prefixes in the triples and query tab

**Comment by MadsHolten** [comment]
Prefixes implemented and columns after the first one are right aligned.
5px padding added.
Possible to navigate through table.
