### ISSUE TITLE
add title for webpage

### ISSUE THREAD

**Issue by mathib** [MadsHolten/sparql-visualizer#9]
It can be useful if the name of the `data.json` file is used as the title for the webpage of the app. If people share JSON files, the data.json file name should be used as the title of the app (visible all the time).

This can be useful if you have the app open in multiple browser windows, each of them referring to another `data.json` file and thus another use case.

**Comment by MadsHolten** [comment]
This has now been added. The format of the JSON is now the following:
{
    "project": {
        "title": "Some project title",
        "creator": "Mads Holten Rasmussen" //optional
    },
    "settings": {
        "filePath": "path to location where triples are located" //optional
    },
    "tabs": [ 
        // Content of old JSON
        {
            "title": "Tab title",
            "description": "Tab description",
            "query": "SPARQL query", //optional
            "triples": "Turtle format triples" //optional
        }
    ]
}

As you can see I also added support for triples stored in a file. This is quite useful in combination with data generated with @jyrkioraskari's tool [IFCtoLBD](https://github.com/jyrkioraskari/IFCtoLBD). Currently this is only supported if you use a SPARQL endpoint though.
